plugins:
  - jekyll-paginate

title: "Alp Şakacı"
description: > # this means to ignore newlines until "email:"
   Software Engineer. <br>
   Amateur Bassist. <br>
   <small><i>Computer Science and Music work in harmony.</i></small>

email: alpsakaci@protonmail.com
logo: "/assets/images/logo.png"
float_logo: true
cover: "/assets/images/header.png"
name: 'Alp Şakacı'
author: 'Alp Şakacı'
author_image: "/assets/images/profile.jpg"
paginate:	5
url: "https://alpsakaci.com"
baseurl: ""
twitter_handle: '@megalpdeth'
google_analytics: UA-139163516-1

social:
  - icon: instagram
    url: https://instagram.com/alp.sakaci/
    
  - icon:	linkedin
    url:	https://www.linkedin.com/in/alpsakaci/

  - icon:	github
    url:	https://github.com/alpsakaci/

  - icon:	envelope-o
    url:	mailto:alpsakaci@protonmail.com
